# Generated by Django 4.1.1 on 2023-08-02 06:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='weight')),
                ('price', models.IntegerField(verbose_name='price')),
                ('discounted_price', models.IntegerField(default=0, verbose_name='discounted price')),
                ('image', models.ImageField(default='', upload_to='product/', verbose_name='image')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
