# Generated by Django 4.1.1 on 2023-08-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_weight_product_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='product',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='is favorite'),
        ),
    ]
