# Generated by Django 4.1.1 on 2023-08-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_customer_order_remove_product_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutdetail',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_product',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature',
            field=models.BooleanField(default=False),
        ),
    ]
