# Generated by Django 4.1.1 on 2023-08-08 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.customer'),
        ),
    ]
